import type { BodyNode, SimFlow } from './simTypes'

export const BODY_NODES: BodyNode[] = [
  {
    id: 'subject', label: 'Classified Subject', objectType: 'Human Actor', systemLayer: 'body',
    x: 355, y: 229, r: 22, color: '#60a5fa', nodeRole: 'actor', baseLoad: 55,
    metrics: { FDCR: 42, BGR: 38, RCI: 35, MSJR: 65 },
    affectedActors: 'Primary subject of classification', affectedScale: 'Individual',
    burdenPathway: 'Classification outcome directly determines access to housing, employment, services',
    reentryCondition: 'Appeal requires legal representation and 90-day waiting period',
    classificationRisk: 'High — demographic proxies embedded in scoring',
    lifeworldImpact: 'Chronic stress from administrative uncertainty; identity fragmentation',
    ecologicalImpact: 'Urban heat burden concentrated in low-FDCR zones',
    correctionMechanism: 'Legal challenge; social worker advocacy; political mobilization',
    scenarioInterpretation: 'Reform reduces classification burden; intensification deepens surveillance loop',
  },
  {
    id: 'nervous', label: 'Neurological Stress', objectType: 'Bodily System', systemLayer: 'body',
    x: 355, y: 148, r: 16, color: '#fbbf24', nodeRole: 'burden', baseLoad: 68,
    metrics: { BGR: 32, BTR: 72 },
    affectedActors: 'Classified individuals under chronic administrative stress',
    affectedScale: 'Individual',
    burdenPathway: 'Chronic uncertainty activates HPA axis; cortisol elevation degrades cognition',
    reentryCondition: 'Biological stress response is involuntary; cannot be appealed',
    classificationRisk: 'Medium — stress response affects compliance behavior, misread as non-cooperation',
    lifeworldImpact: 'Sleep disruption; attention deficits; relationship strain',
    ecologicalImpact: 'Minimal direct ecological impact',
    correctionMechanism: 'Mental health support; reduced administrative uncertainty',
    scenarioInterpretation: 'Reform reduces chronic stress load; intensification worsens neurological burden',
  },
  {
    id: 'respiratory', label: 'Respiratory System', objectType: 'Bodily System', systemLayer: 'body',
    x: 280, y: 185, r: 14, color: '#f97316', nodeRole: 'burden', baseLoad: 62,
    metrics: { BGR: 35, EER: 40 },
    affectedActors: 'Low-income populations in high-pollution zones',
    affectedScale: 'Community',
    burdenPathway: 'Exclusion zone residence correlates with industrial pollution exposure',
    reentryCondition: 'Lung damage is partially irreversible; residential options constrained by classification',
    classificationRisk: 'High — residential classification determines pollution exposure',
    lifeworldImpact: 'Reduced work capacity; medical costs; shortened life expectancy',
    ecologicalImpact: 'Industrial zone air quality directly burdens respiratory health',
    correctionMechanism: 'Environmental justice zoning; pollution regulation enforcement',
    scenarioInterpretation: 'Reform improves zoning equity; intensification concentrates pollution burden',
  },
  {
    id: 'digestive', label: 'Nutritional Access', objectType: 'Bodily System', systemLayer: 'body',
    x: 355, y: 300, r: 14, color: '#f97316', nodeRole: 'burden', baseLoad: 58,
    metrics: { BGR: 38, RCI: 42 },
    affectedActors: 'Benefit-denied individuals and families',
    affectedScale: 'Household',
    burdenPathway: 'Welfare classification denial → food insecurity → malnutrition cascade',
    reentryCondition: 'Nutritional deficits in children create permanent developmental burden',
    classificationRisk: 'High — algorithmic welfare denial disproportionately affects single parents',
    lifeworldImpact: 'Hunger; developmental delays in children; chronic illness',
    ecologicalImpact: 'Food desert geography overlaps with ecological degradation zones',
    correctionMechanism: 'Universal food access programs; benefit denial override mechanisms',
    scenarioInterpretation: 'Reform restores food access; intensification tightens eligibility algorithms',
  },
  {
    id: 'mobility', label: 'Physical Mobility', objectType: 'Bodily System', systemLayer: 'body',
    x: 430, y: 270, r: 14, color: '#a78bfa', nodeRole: 'freedom', baseLoad: 48,
    metrics: { FDCR: 52, RCI: 55 },
    affectedActors: 'Workers dependent on transit access',
    affectedScale: 'Community',
    burdenPathway: 'Transit classification restricts movement; surveillance checkpoints create avoidance behavior',
    reentryCondition: 'Geographic mobility constrained by surveillance zone designations',
    classificationRisk: 'Medium — movement patterns used as behavioral classification input',
    lifeworldImpact: 'Employment access limited by transit restrictions; social isolation',
    ecologicalImpact: 'Car dependency forced by transit exclusions increases emissions',
    correctionMechanism: 'Universal transit access; movement surveillance restrictions',
    scenarioInterpretation: 'Reform expands transit access; intensification adds checkpoint density',
  },
  {
    id: 'identity', label: 'Legal Identity', objectType: 'Administrative Status', systemLayer: 'body',
    x: 430, y: 185, r: 16, color: '#34d399', nodeRole: 'barrier', baseLoad: 35,
    metrics: { FDCR: 38, RCI: 32, DRR: 44 },
    affectedActors: 'Undocumented persons, stateless individuals, identity fraud victims',
    affectedScale: 'Individual',
    burdenPathway: 'Document requirements for every service interaction; identity verification failures cascade',
    reentryCondition: 'Identity document errors require months of administrative correction',
    classificationRisk: 'Very high — identity is the primary classification variable in all systems',
    lifeworldImpact: 'Administrative invisibility; inability to access emergency services without identity proof',
    ecologicalImpact: 'Climate displacement creates statelessness; identity systems not adapted',
    correctionMechanism: 'Identity verification reform; emergency access provisions; legal aid',
    scenarioInterpretation: 'Reform creates accessible identity repair; intensification mandates stricter verification',
  },
  {
    id: 'shelter', label: 'Housing Security', objectType: 'Material Condition', systemLayer: 'body',
    x: 280, y: 270, r: 16, color: '#fb7185', nodeRole: 'burden', baseLoad: 42,
    metrics: { FDCR: 40, BGR: 36, RCI: 38 },
    affectedActors: 'Renters, informal settlers, benefit recipients',
    affectedScale: 'Household',
    burdenPathway: 'Eviction classification creates permanent rental record; AI landlord screening excludes',
    reentryCondition: 'Eviction record persists for 7 years; no expungement mechanism',
    classificationRisk: 'High — rental AI uses criminal and credit data as proxies for race',
    lifeworldImpact: 'Housing instability → school disruption → employment precarity cascade',
    ecologicalImpact: 'Homelessness concentrates in flood-prone low-value land',
    correctionMechanism: 'Eviction record sealing; source-of-income protections; tenant AI audits',
    scenarioInterpretation: 'Reform seals eviction records; intensification expands AI landlord screening',
  },
  {
    id: 'care', label: 'Care Network', objectType: 'Social Infrastructure', systemLayer: 'body',
    x: 200, y: 229, r: 14, color: '#34d399', nodeRole: 'sustain', baseLoad: 60,
    metrics: { FDCR: 58, BGR: 55, RCI: 52 },
    affectedActors: 'Informal caregivers, community mutual aid networks',
    affectedScale: 'Community',
    burdenPathway: 'Classification undermines trust; community members fear surveillance through association',
    reentryCondition: 'Surveillance chilling effect reduces mutual aid participation',
    classificationRisk: 'Medium — care networks classified as security risks in some jurisdictions',
    lifeworldImpact: 'Social isolation when care networks fragment; mental health deterioration',
    ecologicalImpact: 'Community gardens and informal food systems disrupted by exclusion zoning',
    correctionMechanism: 'Community organizing protections; surveillance limitation laws',
    scenarioInterpretation: 'Reform protects care networks; intensification surveils and disrupts them',
  },
  {
    id: 'voice', label: 'Expressive Agency', objectType: 'Political Capacity', systemLayer: 'body',
    x: 510, y: 229, r: 14, color: '#a78bfa', nodeRole: 'freedom', baseLoad: 38,
    metrics: { FDCR: 44, RCI: 40, MSJR: 60 },
    affectedActors: 'Classified individuals, community advocates, whistleblowers',
    affectedScale: 'Community-Political',
    burdenPathway: 'Classification outcomes suppress speech; fear of worsened status chills advocacy',
    reentryCondition: 'Retaliation risk in classification systems for those who contest decisions',
    classificationRisk: 'High — advocacy activity classified as risk factor in some systems',
    lifeworldImpact: 'Self-censorship; reduced political participation; democratic erosion',
    ecologicalImpact: 'Environmental defenders facing surveillance and classification retaliation',
    correctionMechanism: 'Whistleblower protections; anti-retaliation classification rules',
    scenarioInterpretation: 'Reform strengthens expressive protections; intensification classifies dissent as risk',
  },
  {
    id: 'time', label: 'Temporal Burden', objectType: 'Administrative Burden', systemLayer: 'body',
    x: 355, y: 390, r: 14, color: '#f97316', nodeRole: 'compress', baseLoad: 75,
    metrics: { BTR: 78, MSJR: 70, CFR: 65 },
    affectedActors: 'All classified individuals navigating administrative processes',
    affectedScale: 'Individual',
    burdenPathway: 'Compliance documentation consumes work hours, childcare hours, sleep time',
    reentryCondition: 'Administrative deadlines create irreversible status losses',
    classificationRisk: 'High — documentation failure classified as non-compliance',
    lifeworldImpact: 'Exhaustion; family time compression; health maintenance neglect',
    ecologicalImpact: 'Travel to in-person appointments in under-served areas increases emissions',
    correctionMechanism: 'Simplified documentation; extended deadlines; digital-first options',
    scenarioInterpretation: 'Reform reduces documentation burden; intensification adds verification requirements',
  },
  {
    id: 'memory', label: 'Institutional Memory', objectType: 'Data Infrastructure', systemLayer: 'body',
    x: 200, y: 310, r: 12, color: '#ef4444', nodeRole: 'barrier', baseLoad: 82,
    metrics: { RCI: 28, DRR: 35, MSJR: 78 },
    affectedActors: 'Anyone with historical classification record',
    affectedScale: 'Systemic',
    burdenPathway: 'Prior classifications stored indefinitely and resurface in new system interactions',
    reentryCondition: 'No right to erasure in law enforcement and welfare databases',
    classificationRisk: 'Very high — historical misclassification propagates forward',
    lifeworldImpact: 'Permanent record haunts employment, housing, credit, and custody decisions',
    ecologicalImpact: 'Long-term data storage energy cost; data center land use',
    correctionMechanism: 'Data minimization laws; right to erasure; statute of limitations on records',
    scenarioInterpretation: 'Reform enacts data minimization; intensification expands indefinite retention',
  },
  {
    id: 'health', label: 'Health Access', objectType: 'Service Access', systemLayer: 'body',
    x: 510, y: 148, r: 14, color: '#fb7185', nodeRole: 'burden', baseLoad: 50,
    metrics: { BGR: 42, FDCR: 46, RCI: 44 },
    affectedActors: 'Uninsured, undocumented, benefit-denied individuals',
    affectedScale: 'Individual-Community',
    burdenPathway: 'Insurance classification gatekeeping prevents care access; debt from uninsured care',
    reentryCondition: 'Medical debt classifications persist; bankruptcy cannot fully discharge',
    classificationRisk: 'High — health AI used for prior authorization denial',
    lifeworldImpact: 'Delayed treatment worsens conditions; preventable deaths from classification denial',
    ecologicalImpact: 'Environmental illness disproportionately affects those denied health access',
    correctionMechanism: 'Universal health access; prior authorization AI auditing',
    scenarioInterpretation: 'Reform expands coverage; intensification tightens insurance AI gatekeeping',
  },
  {
    id: 'education', label: 'Education Access', objectType: 'Service Access', systemLayer: 'body',
    x: 510, y: 310, r: 14, color: '#34d399', nodeRole: 'sustain', baseLoad: 55,
    metrics: { FDCR: 50, FGR: 52, RCI: 48 },
    affectedActors: 'Children of classified parents, student loan holders',
    affectedScale: 'Generational',
    burdenPathway: 'Parental classification affects school enrollment; student debt classification limits mobility',
    reentryCondition: 'Educational credential recognition blocked by nationality classification',
    classificationRisk: 'Medium-high — predictive discipline AI in schools creates early-life classification',
    lifeworldImpact: 'Intergenerational burden; foreclosed futures; talent suppression',
    ecologicalImpact: 'School location in exclusion zones correlates with environmental hazards',
    correctionMechanism: 'Educational equity funding; predictive discipline AI bans',
    scenarioInterpretation: 'Reform invests in education equity; intensification expands predictive school AI',
  },
  {
    id: 'autonomy', label: 'Bodily Autonomy', objectType: 'Fundamental Right', systemLayer: 'body',
    x: 200, y: 148, r: 16, color: '#60a5fa', nodeRole: 'freedom', baseLoad: 40,
    metrics: { FDCR: 46, BGR: 40, EBDCR: 38 },
    affectedActors: 'All persons subject to classification systems',
    affectedScale: 'Universal',
    burdenPathway: 'Classification overrides bodily sovereignty; forced compliance behavior',
    reentryCondition: 'Autonomy restoration requires systemic change, not individual appeal',
    classificationRisk: 'Foundational — autonomy is what classification systems most structurally threaten',
    lifeworldImpact: 'Existential unfreedom; reduced sense of agency and self-determination',
    ecologicalImpact: 'Bodily autonomy of future generations contingent on current ecological choices',
    correctionMechanism: 'Constitutional rights enforcement; bodily autonomy as legal category in AI law',
    scenarioInterpretation: 'Reform centers bodily autonomy in AI governance; intensification treats compliance as obligation',
  },
]

export const BODY_EDGES: SimFlow[] = [
  { id: 'be1', source: 'subject', target: 'nervous', flowType: 'burden', severity: 75, opacity: 0.8, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Classification stress activates chronic neurological burden' },
  { id: 'be2', source: 'subject', target: 'identity', flowType: 'barrier', severity: 80, opacity: 0.85, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Legal identity mediation required for all service access' },
  { id: 'be3', source: 'identity', target: 'shelter', flowType: 'burden', severity: 70, opacity: 0.8, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Identity status gates rental and housing access' },
  { id: 'be4', source: 'identity', target: 'health', flowType: 'burden', severity: 65, opacity: 0.75, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Insurance classification requires identity verification' },
  { id: 'be5', source: 'nervous', target: 'respiratory', flowType: 'burden', severity: 60, opacity: 0.7, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Stress compounds respiratory burden from pollution exposure' },
  { id: 'be6', source: 'shelter', target: 'digestive', flowType: 'burden', severity: 72, opacity: 0.8, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Housing instability leads to food insecurity' },
  { id: 'be7', source: 'care', target: 'subject', flowType: 'freedom', severity: 55, opacity: 0.7, reversibility: 'reversible', affectedLayer: 'body', explanation: 'Care networks provide resilience buffer' },
  { id: 'be8', source: 'voice', target: 'subject', flowType: 'freedom', severity: 48, opacity: 0.65, reversibility: 'reversible', affectedLayer: 'body', explanation: 'Expressive agency enables self-advocacy' },
  { id: 'be9', source: 'time', target: 'subject', flowType: 'compress', severity: 80, opacity: 0.85, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Administrative time burden compresses all other life activities' },
  { id: 'be10', source: 'memory', target: 'identity', flowType: 'barrier', severity: 85, opacity: 0.9, reversibility: 'terminal', affectedLayer: 'body', explanation: 'Institutional memory enforces permanent historical classification' },
  { id: 'be11', source: 'mobility', target: 'care', flowType: 'freedom', severity: 52, opacity: 0.65, reversibility: 'reversible', affectedLayer: 'body', explanation: 'Physical mobility enables care network maintenance' },
  { id: 'be12', source: 'education', target: 'subject', flowType: 'freedom', severity: 58, opacity: 0.7, reversibility: 'reversible', affectedLayer: 'body', explanation: 'Education access opens re-entry pathways' },
  { id: 'be13', source: 'autonomy', target: 'subject', flowType: 'freedom', severity: 45, opacity: 0.6, reversibility: 'reversible', affectedLayer: 'body', explanation: 'Bodily autonomy is foundational to freedom-correctness' },
  { id: 'be14', source: 'subject', target: 'time', flowType: 'burden', severity: 70, opacity: 0.75, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Subject bears all administrative compliance time costs' },
  { id: 'be15', source: 'health', target: 'nervous', flowType: 'burden', severity: 62, opacity: 0.7, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Health access denial compounds neurological stress' },
  { id: 'be16', source: 'shelter', target: 'mobility', flowType: 'burden', severity: 55, opacity: 0.65, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Housing location constrains mobility options' },
  { id: 'be17', source: 'digestive', target: 'autonomy', flowType: 'burden', severity: 68, opacity: 0.75, reversibility: 'constrained', affectedLayer: 'body', explanation: 'Food insecurity undermines capacity for autonomous action' },
]
