import type { FlowNode, SimFlow } from './simTypes'

export const FLOW_NODES: FlowNode[] = [
  {
    id: 'entry', label: 'System Entry', objectType: 'Entry Point', systemLayer: 'flow',
    x: 355, y: 45, shape: 'diamond', color: '#60a5fa',
    tagCode: 'E-01', tagLabel: 'Entry',
    metrics: { FDCR: 55, RCI: 50 },
    affectedActors: 'All applicants entering classification system',
    affectedScale: 'Systemic',
    burdenPathway: 'Entry documentation requirements create first barrier; digital exclusion at portal',
    reentryCondition: 'Re-entry after rejection requires full reapplication with same barriers',
    classificationRisk: 'Medium — entry data collection begins classification before formal review',
    lifeworldImpact: 'First contact often humiliating; creates anticipatory anxiety and avoidance',
    ecologicalImpact: 'Physical office visits required in low-bandwidth areas increase travel burden',
    correctionMechanism: 'Simplified entry portals; multiple access modalities; language access',
    scenarioInterpretation: 'Reform creates streamlined equitable entry; intensification adds verification hurdles at entry',
  },
  {
    id: 'intake', label: 'Intake Processing', objectType: 'Administrative Stage', systemLayer: 'flow',
    x: 240, y: 104, shape: 'rect', color: '#fbbf24',
    tagCode: 'I-01', tagLabel: 'Intake',
    metrics: { FDCR: 50, MSJR: 58, CFR: 52 },
    affectedActors: 'Case workers, automated intake systems, applicants',
    affectedScale: 'Institutional',
    burdenPathway: 'Intake errors propagate through entire process; documentation incompleteness triggers rejection',
    reentryCondition: 'Incomplete intake requires restart; no partial credit for prior documentation',
    classificationRisk: 'High — intake flags drive downstream AI classification inputs',
    lifeworldImpact: 'Multiple visits required; time off work; childcare costs for appointments',
    ecologicalImpact: 'Paper-based systems create document production and disposal burden',
    correctionMechanism: 'Intake error review; ombudsman access at intake stage',
    scenarioInterpretation: 'Reform digitizes intake with human override; intensification automates with no override',
  },
  {
    id: 'verify', label: 'Identity Verification', objectType: 'Administrative Stage', systemLayer: 'flow',
    x: 470, y: 104, shape: 'rect', color: '#fbbf24',
    tagCode: 'V-01', tagLabel: 'Verify',
    metrics: { FDCR: 45, MSJR: 65, RCI: 40, DRR: 55 },
    affectedActors: 'Document checkers, biometric systems, stateless persons',
    affectedScale: 'Individual',
    burdenPathway: 'Biometric failure rate disproportionate for dark skin tones; document requirements exclude',
    reentryCondition: 'Verification failure blocks all downstream steps until resolved',
    classificationRisk: 'Very high — biometric systems encode demographic bias',
    lifeworldImpact: 'Repeated biometric attempts cause distress; failures generate shame',
    ecologicalImpact: 'Biometric database infrastructure energy consumption',
    correctionMechanism: 'Manual verification override; bias auditing of biometric systems',
    scenarioInterpretation: 'Reform mandates bias auditing; intensification expands biometric requirement scope',
  },
  {
    id: 'ai_process', label: 'AI Risk Scoring', objectType: 'Automated Decision System', systemLayer: 'flow',
    x: 355, y: 163, shape: 'hexagon', color: '#a78bfa',
    tagCode: 'AI-01', tagLabel: 'AI Score',
    metrics: { FDCR: 32, MSJR: 78, CFR: 72, RBR: 68, EPBTM: 74 },
    affectedActors: 'All applicants; disproportionately affects racial minorities',
    affectedScale: 'Systemic',
    burdenPathway: 'Opaque risk score determines eligibility; score informed by proxy variables for protected characteristics',
    reentryCondition: 'Score persists in system; recalculation requires administrative request taking 60+ days',
    classificationRisk: 'Extreme — AI score is primary classification determinant',
    lifeworldImpact: 'Invisible judgment with visible consequences; impossible to contest opaque score',
    ecologicalImpact: 'GPU inference energy per decision; model training carbon cost amortized across decisions',
    correctionMechanism: 'Algorithmic transparency; mandatory explanation; independent audit',
    scenarioInterpretation: 'Reform mandates explainability and human review; intensification expands AI scope with less oversight',
  },
  {
    id: 'class_high', label: 'High-Risk Classification', objectType: 'Classification Output', systemLayer: 'flow',
    x: 190, y: 222, shape: 'rect', color: '#ef4444',
    tagCode: 'C-H', tagLabel: 'High Risk',
    metrics: { FDCR: 18, MSJR: 88, CFR: 85, RBR: 82, BTR: 90 },
    affectedActors: 'Classified as high-risk; disproportionately minority communities',
    affectedScale: 'Individual-Community',
    burdenPathway: 'High-risk label triggers surveillance, benefit denial, border flagging, and housing exclusion',
    reentryCondition: 'Label requires 2+ years and legal representation to contest',
    classificationRisk: 'Maximum — high-risk label is the primary burden transfer mechanism',
    lifeworldImpact: 'Pervasive exclusion from services; constant surveillance; fear of interaction with institutions',
    ecologicalImpact: 'High-risk labeling confines to most ecologically burdened zones',
    correctionMechanism: 'Mandatory review periods; automatic appeal; legal aid entitlement at classification',
    scenarioInterpretation: 'Reform eliminates binary high/low risk; intensification expands high-risk category scope',
  },
  {
    id: 'class_med', label: 'Medium-Risk Classification', objectType: 'Classification Output', systemLayer: 'flow',
    x: 355, y: 222, shape: 'rect', color: '#f97316',
    tagCode: 'C-M', tagLabel: 'Med Risk',
    metrics: { FDCR: 38, MSJR: 65, CFR: 60, RBR: 55 },
    affectedActors: 'Mid-tier classified individuals facing conditional access',
    affectedScale: 'Individual',
    burdenPathway: 'Conditional access requires ongoing compliance documentation; reclassification to high-risk is common',
    reentryCondition: 'Conditional status requires periodic re-verification with full documentation burden',
    classificationRisk: 'High — medium classification is an unstable holding pattern, not a stable state',
    lifeworldImpact: 'Chronic uncertainty; planning for future impossible under conditional status',
    ecologicalImpact: 'Conditional housing access forces residence in environmentally burdened areas',
    correctionMechanism: 'Clear reclassification criteria; time-limited conditional status; automatic review',
    scenarioInterpretation: 'Reform creates clearer pathways to low-risk; intensification makes medium-risk a trap',
  },
  {
    id: 'class_low', label: 'Low-Risk Classification', objectType: 'Classification Output', systemLayer: 'flow',
    x: 520, y: 222, shape: 'rect', color: '#4ade80',
    tagCode: 'C-L', tagLabel: 'Low Risk',
    metrics: { FDCR: 68, MSJR: 35, CFR: 30, RBR: 25 },
    affectedActors: 'Low-risk classified individuals with service access',
    affectedScale: 'Individual',
    burdenPathway: 'Low-risk status provides access but can be revoked by system update without notice',
    reentryCondition: 'Status revocation can happen without triggering formal appeal rights',
    classificationRisk: 'Low-moderate — low-risk status not permanently secure',
    lifeworldImpact: 'Relatively stable access but subject to reassessment; advantage accrues to already-advantaged',
    ecologicalImpact: 'Low-risk residential areas have better environmental quality',
    correctionMechanism: 'Status stability guarantees; notification requirements before revocation',
    scenarioInterpretation: 'Reform makes low-risk status more stable and portable; intensification makes it more contingent',
  },
  {
    id: 'human_review', label: 'Human Review', objectType: 'Override Mechanism', systemLayer: 'flow',
    x: 190, y: 281, shape: 'circle', color: '#34d399',
    tagCode: 'HR-01', tagLabel: 'Review',
    metrics: { FDCR: 58, RCI: 55, DRR: 60 },
    affectedActors: 'Case workers, supervisors, ombudspersons',
    affectedScale: 'Individual',
    burdenPathway: 'Human review capacity overwhelmed; average wait 120 days; review rubber-stamps AI decision 78% of time',
    reentryCondition: 'Review request does not pause enforcement of classification consequences',
    classificationRisk: 'Medium — human reviewers share AI biases but can be trained',
    lifeworldImpact: 'Hope for review creates waiting burden; outcome often same as AI decision',
    ecologicalImpact: 'Physical review office access requires travel',
    correctionMechanism: 'Funded review capacity; mandatory AI override training; adverse inference rules',
    scenarioInterpretation: 'Reform funds and empowers review; intensification defunds and marginalizes it',
  },
  {
    id: 'appeal', label: 'Formal Appeal', objectType: 'Legal Mechanism', systemLayer: 'flow',
    x: 355, y: 340, shape: 'diamond', color: '#60a5fa',
    tagCode: 'AP-01', tagLabel: 'Appeal',
    metrics: { FDCR: 50, RCI: 48, DRR: 52 },
    affectedActors: 'Applicants with legal representation; self-represented appellants disadvantaged',
    affectedScale: 'Individual',
    burdenPathway: 'Appeal requires legal knowledge, documentation, and time; 60% of unrepresented appeals fail',
    reentryCondition: 'Failed appeal creates shorter re-appeal window; risk of case closure',
    classificationRisk: 'Medium — appeals can correct individual cases but do not change systemic patterns',
    lifeworldImpact: 'Legal stress; costs; relationship strain during long appeal period',
    ecologicalImpact: 'In-person hearing requirements create travel burden',
    correctionMechanism: 'Legal aid entitlement; simplified appeal forms; digital appeal options',
    scenarioInterpretation: 'Reform creates accessible appeal; intensification adds procedural barriers to appeal',
  },
  {
    id: 'deny_final', label: 'Final Denial', objectType: 'Terminal Outcome', systemLayer: 'flow',
    x: 190, y: 390, shape: 'rect', color: '#ef4444',
    tagCode: 'D-01', tagLabel: 'Denied',
    metrics: { FDCR: 12, RCI: 10, BTR: 95, MSJR: 92 },
    affectedActors: 'Permanently excluded individuals; families',
    affectedScale: 'Individual-Generational',
    burdenPathway: 'Final denial triggers multi-system cascades: housing, employment, healthcare, childcare all affected',
    reentryCondition: 'Terminal — no re-entry pathway without extraordinary legal action',
    classificationRisk: 'Maximum — final denial is the most severe classification outcome',
    lifeworldImpact: 'Existential crisis; family dissolution; homeless risk; deportation',
    ecologicalImpact: 'Exclusion concentrates denied individuals in most ecologically precarious zones',
    correctionMechanism: 'Class action litigation; legislative override; political mobilization',
    scenarioInterpretation: 'Reform eliminates terminal denial without pathway; intensification expands final denial scope',
  },
  {
    id: 'bypass', label: 'AI Bypass Route', objectType: 'Procedural Shortcut', systemLayer: 'flow',
    x: 520, y: 281, shape: 'circle', color: '#f97316',
    tagCode: 'BP-01', tagLabel: 'Bypass',
    metrics: { FDCR: 35, MSJR: 75, CFR: 70, RBR: 72 },
    affectedActors: 'High-volume cases routed through automated pipeline without human contact',
    affectedScale: 'Systemic',
    burdenPathway: 'AI bypass routes high-volume cases directly to denial without human review trigger',
    reentryCondition: 'Bypass cases have no automatic review; must self-identify as bypassed to appeal',
    classificationRisk: 'Very high — bypass is the highest-volume path and lowest-scrutiny path',
    lifeworldImpact: 'Invisible bureaucratic action with no notice; denial arrives by post',
    ecologicalImpact: 'Automated processing concentrates burden on those already in ecologically stressed areas',
    correctionMechanism: 'Mandatory human review for all denials; bypass identification disclosure',
    scenarioInterpretation: 'Reform eliminates bypass; intensification expands bypass to 80%+ of volume',
  },
  {
    id: 'approve', label: 'Approval', objectType: 'Positive Outcome', systemLayer: 'flow',
    x: 520, y: 390, shape: 'rect', color: '#4ade80',
    tagCode: 'A-01', tagLabel: 'Approved',
    metrics: { FDCR: 72, RCI: 68, FGR: 65 },
    affectedActors: 'Successfully classified individuals receiving services',
    affectedScale: 'Individual',
    burdenPathway: 'Approval still contingent; status reviewed periodically; compliance monitoring continues',
    reentryCondition: 'Approval is temporary; renewal burden recurs annually or more frequently',
    classificationRisk: 'Low — but renewal requirements create perpetual classification exposure',
    lifeworldImpact: 'Relative stability but ongoing compliance documentation burden',
    ecologicalImpact: 'Approved individuals access better environmental conditions',
    correctionMechanism: 'Permanent approval pathways; reduced renewal burden for stable cases',
    scenarioInterpretation: 'Reform creates durable approvals; intensification shortens approval duration and increases renewal barriers',
  },
  {
    id: 'monitor', label: 'Ongoing Monitoring', objectType: 'Surveillance System', systemLayer: 'flow',
    x: 355, y: 420, shape: 'hexagon', color: '#a78bfa',
    tagCode: 'MN-01', tagLabel: 'Monitor',
    metrics: { FDCR: 30, MSJR: 72, BTR: 68, EER: 55, EPBTM: 70 },
    affectedActors: 'All classified individuals; surveillance burden on approved and pending',
    affectedScale: 'Systemic',
    burdenPathway: 'Monitoring data feeds back to AI scoring; behavioral compliance required to maintain classification',
    reentryCondition: 'Monitoring violations trigger automatic reclassification to higher risk tier',
    classificationRisk: 'High — monitoring creates perpetual classification exposure',
    lifeworldImpact: 'Chilling effect on all behavior; self-modification to satisfy algorithmic requirements',
    ecologicalImpact: 'Monitoring infrastructure (cameras, sensors, databases) has significant energy footprint',
    correctionMechanism: 'Monitoring scope limitations; data minimization; judicial oversight of monitoring programs',
    scenarioInterpretation: 'Reform limits monitoring scope and duration; intensification expands to real-time behavioral AI',
  },
  {
    id: 'reentry', label: 'Re-entry Pathway', objectType: 'Correction Mechanism', systemLayer: 'flow',
    x: 190, y: 163, shape: 'circle', color: '#34d399',
    tagCode: 'RE-01', tagLabel: 'Re-entry',
    metrics: { FDCR: 62, RCI: 58, DRR: 65, FGR: 60 },
    affectedActors: 'Previously denied individuals seeking reclassification',
    affectedScale: 'Individual',
    burdenPathway: 'Re-entry requires changed circumstances proof; standard is high and documentation burden is high',
    reentryCondition: 'Re-entry is the key correction mechanism — its accessibility determines system fairness',
    classificationRisk: 'Medium — re-entry pathway itself has classification risk if poorly designed',
    lifeworldImpact: 'Hope creates continued engagement; barriers to re-entry create learned helplessness',
    ecologicalImpact: 'Re-entry success correlates with environmental quality access',
    correctionMechanism: 'This node IS the correction mechanism — its robustness is the metric of system justice',
    scenarioInterpretation: 'Reform makes re-entry accessible and well-resourced; intensification makes it nearly inaccessible',
  },
]

export const FLOW_EDGES: SimFlow[] = [
  { id: 'fe1', source: 'entry', target: 'intake', flowType: 'neutral', severity: 60, opacity: 0.7, reversibility: 'reversible', affectedLayer: 'flow', explanation: 'Entry feeds intake process' },
  { id: 'fe2', source: 'entry', target: 'verify', flowType: 'neutral', severity: 60, opacity: 0.7, reversibility: 'reversible', affectedLayer: 'flow', explanation: 'Entry triggers parallel identity verification' },
  { id: 'fe3', source: 'intake', target: 'ai_process', flowType: 'burden', severity: 72, opacity: 0.8, reversibility: 'constrained', affectedLayer: 'flow', explanation: 'Intake data feeds AI scoring engine' },
  { id: 'fe4', source: 'verify', target: 'ai_process', flowType: 'burden', severity: 68, opacity: 0.75, reversibility: 'constrained', affectedLayer: 'flow', explanation: 'Verification result is key AI input variable' },
  { id: 'fe5', source: 'ai_process', target: 'class_high', flowType: 'burden', severity: 85, opacity: 0.9, reversibility: 'constrained', affectedLayer: 'flow', explanation: 'AI score above threshold triggers high-risk classification' },
  { id: 'fe6', source: 'ai_process', target: 'class_med', flowType: 'burden', severity: 65, opacity: 0.75, reversibility: 'constrained', affectedLayer: 'flow', explanation: 'Mid-range AI score triggers medium classification' },
  { id: 'fe7', source: 'ai_process', target: 'class_low', flowType: 'freedom', severity: 45, opacity: 0.6, reversibility: 'reversible', affectedLayer: 'flow', explanation: 'Low AI score grants low-risk classification' },
  { id: 'fe8', source: 'ai_process', target: 'bypass', flowType: 'barrier', severity: 78, opacity: 0.85, reversibility: 'terminal', affectedLayer: 'flow', explanation: 'High-volume bypass route routes around human review' },
  { id: 'fe9', source: 'class_high', target: 'human_review', flowType: 'neutral', severity: 55, opacity: 0.65, reversibility: 'reversible', affectedLayer: 'flow', explanation: 'High-risk classification triggers human review option' },
  { id: 'fe10', source: 'class_high', target: 'deny_final', flowType: 'burden', severity: 88, opacity: 0.9, reversibility: 'terminal', affectedLayer: 'flow', explanation: 'High-risk without review leads to final denial' },
  { id: 'fe11', source: 'bypass', target: 'deny_final', flowType: 'burden', severity: 82, opacity: 0.9, reversibility: 'terminal', affectedLayer: 'flow', explanation: 'Bypass route ends in automatic denial' },
  { id: 'fe12', source: 'class_low', target: 'approve', flowType: 'freedom', severity: 42, opacity: 0.6, reversibility: 'reversible', affectedLayer: 'flow', explanation: 'Low-risk classification leads to approval' },
  { id: 'fe13', source: 'human_review', target: 'appeal', flowType: 'neutral', severity: 52, opacity: 0.65, reversibility: 'reversible', affectedLayer: 'flow', explanation: 'Review outcome can be appealed' },
  { id: 'fe14', source: 'appeal', target: 'approve', flowType: 'freedom', severity: 48, opacity: 0.6, reversibility: 'reversible', affectedLayer: 'flow', explanation: 'Successful appeal leads to approval' },
  { id: 'fe15', source: 'appeal', target: 'deny_final', flowType: 'burden', severity: 72, opacity: 0.8, reversibility: 'terminal', affectedLayer: 'flow', explanation: 'Failed appeal leads to final denial' },
  { id: 'fe16', source: 'approve', target: 'monitor', flowType: 'burden', severity: 58, opacity: 0.7, reversibility: 'constrained', affectedLayer: 'flow', explanation: 'Approval triggers ongoing monitoring requirement' },
  { id: 'fe17', source: 'monitor', target: 'ai_process', flowType: 'burden', severity: 65, opacity: 0.75, reversibility: 'constrained', affectedLayer: 'flow', explanation: 'Monitoring data feeds back into AI scoring loop' },
  { id: 'fe18', source: 'reentry', target: 'ai_process', flowType: 'freedom', severity: 55, opacity: 0.65, reversibility: 'reversible', affectedLayer: 'flow', explanation: 'Re-entry pathway allows re-classification attempt' },
]
