import type { PlanetaryNode } from './simTypes'

export const GLOBE = { cx: 355, cy: 229, r: 160 }

export function orthoProject(lat: number, lon: number, rotLon = 15): { x: number; y: number; visible: boolean } {
  const phi = (lat * Math.PI) / 180
  const lam = ((lon - rotLon) * Math.PI) / 180
  const cosC = Math.cos(phi) * Math.cos(lam)
  const x = GLOBE.cx + GLOBE.r * Math.cos(phi) * Math.sin(lam)
  const y = GLOBE.cy - GLOBE.r * Math.sin(phi)
  return { x, y, visible: cosC >= 0 }
}

export const CONTINENTS: Array<{ id: string; pts: Array<[number, number]> }> = [
  {
    id: 'NA',
    pts: [
      [70, -140], [72, -95], [65, -80], [60, -65], [47, -53], [45, -66],
      [44, -76], [42, -83], [30, -88], [26, -97], [22, -110], [28, -118],
      [38, -125], [50, -127], [60, -140], [70, -140],
    ],
  },
  {
    id: 'SA',
    pts: [
      [12, -72], [10, -62], [5, -52], [-5, -35], [-15, -39], [-22, -43],
      [-34, -58], [-55, -68], [-55, -64], [-38, -57], [-28, -49], [-15, -75],
      [-5, -80], [5, -77], [10, -75], [12, -72],
    ],
  },
  {
    id: 'EU',
    pts: [
      [71, 28], [68, 20], [60, 5], [51, 2], [43, -9], [37, -8],
      [36, 10], [38, 26], [42, 28], [46, 30], [55, 24], [60, 25],
      [65, 28], [71, 28],
    ],
  },
  {
    id: 'AF',
    pts: [
      [37, -5], [37, 10], [30, 32], [20, 38], [10, 42], [0, 42],
      [-10, 40], [-20, 35], [-34, 26], [-35, 18], [-22, 14], [-5, 8],
      [5, 0], [5, -8], [15, -17], [25, -15], [37, -5],
    ],
  },
  {
    id: 'AS',
    pts: [
      [72, 60], [70, 90], [65, 130], [55, 140], [42, 140], [35, 130],
      [22, 114], [10, 105], [1, 104], [10, 80], [20, 73], [25, 57],
      [30, 48], [38, 26], [42, 28], [55, 24], [60, 25], [65, 50],
      [72, 60],
    ],
  },
  {
    id: 'OC',
    pts: [
      [-15, 130], [-10, 143], [-20, 148], [-33, 152], [-38, 146],
      [-38, 140], [-30, 114], [-22, 114], [-15, 130],
    ],
  },
]

export const PLANETARY_NODES: PlanetaryNode[] = [
  {
    id: 'NA', label: 'North America', objectType: 'Region', systemLayer: 'planetary',
    lat: 45, lon: -100, nodeCategory: 'region',
    metrics: { FDCR: 52, GFDCR: 48, EFDCR: 45, BTR: 55, EER: 42, FGR: 50 },
    affectedActors: 'Migrants, welfare recipients, gig workers',
    affectedScale: 'Continental',
    burdenPathway: 'Algorithmic classification cascades through federal systems into state welfare and border agencies',
    reentryCondition: 'Appeals blocked by multi-agency data sharing; no single point of correction',
    classificationRisk: 'High — demographic proxy variables embedded in hiring and benefits systems',
    lifeworldImpact: 'Chronic administrative precarity; digital identity fragmentation',
    ecologicalImpact: 'Data center energy load concentrated in water-stressed zones',
    correctionMechanism: 'Algorithmic impact assessments; independent audit boards',
    scenarioInterpretation: 'Reform scenario opens re-entry pathways; intensification accelerates exclusion cascades',
  },
  {
    id: 'EU', label: 'Europe', objectType: 'Region', systemLayer: 'planetary',
    lat: 52, lon: 15, nodeCategory: 'region',
    metrics: { FDCR: 61, GFDCR: 58, EFDCR: 55, BTR: 48, EER: 50, FGR: 58 },
    affectedActors: 'Asylum seekers, undocumented residents, platform workers',
    affectedScale: 'Continental',
    burdenPathway: 'Eurodac biometric sharing enables tracking across member states; deportation coordination',
    reentryCondition: 'Schengen exclusion lists create territorial re-entry blocks with limited appeal',
    classificationRisk: 'Moderate-high — GDPR partially mitigates but enforcement gaps persist',
    lifeworldImpact: 'Legal identity instability; housing and employment access contingent on status',
    ecologicalImpact: 'Offshore data centers; e-waste burden transferred to Global South',
    correctionMechanism: 'EU AI Act enforcement; data protection authority interventions',
    scenarioInterpretation: 'Reform scenario strengthens GDPR; intensification expands Eurodac scope',
  },
  {
    id: 'AS', label: 'Asia-Pacific', objectType: 'Region', systemLayer: 'planetary',
    lat: 30, lon: 100, nodeCategory: 'region',
    metrics: { FDCR: 38, GFDCR: 35, EFDCR: 32, BTR: 68, EER: 38, FGR: 40 },
    affectedActors: 'Migrant workers, ethnic minorities, political dissidents',
    affectedScale: 'Continental',
    burdenPathway: 'Social credit and surveillance infrastructure exported regionally; labor migration classification',
    reentryCondition: 'State-level digital identity revocation; no transnational appeal mechanism',
    classificationRisk: 'Very high — facial recognition and behavioral scoring integrated into state systems',
    lifeworldImpact: 'Pervasive behavioral modification; chilling effect on association and expression',
    ecologicalImpact: 'Manufacturing supply chains of AI hardware; rare-earth extraction burden',
    correctionMechanism: 'International human rights mechanisms; civil society monitoring',
    scenarioInterpretation: 'Reform scenario builds regional data rights frameworks; intensification exports surveillance models',
  },
  {
    id: 'LA', label: 'Latin America', objectType: 'Region', systemLayer: 'planetary',
    lat: -15, lon: -60, nodeCategory: 'region',
    metrics: { FDCR: 43, GFDCR: 40, EFDCR: 37, BTR: 62, EER: 44, FGR: 46 },
    affectedActors: 'Indigenous communities, informal workers, climate migrants',
    affectedScale: 'Continental',
    burdenPathway: 'Extraction-linked displacement; biometric border systems funded by Global North',
    reentryCondition: 'Statelessness risk for displaced indigenous populations',
    classificationRisk: 'High — immigration AI systems imported without local accountability',
    lifeworldImpact: 'Land dispossession tied to algorithmic resource mapping',
    ecologicalImpact: 'Amazon deforestation data used in carbon offset systems without community consent',
    correctionMechanism: 'Indigenous land rights legal frameworks; IACHR petitions',
    scenarioInterpretation: 'Reform scenario funds community-controlled data; intensification accelerates extraction',
  },
  {
    id: 'AF', label: 'Africa', objectType: 'Region', systemLayer: 'planetary',
    lat: 5, lon: 20, nodeCategory: 'region',
    metrics: { FDCR: 35, GFDCR: 32, EFDCR: 29, BTR: 71, EER: 40, FGR: 38 },
    affectedActors: 'Refugees, stateless persons, smallholder farmers',
    affectedScale: 'Continental',
    burdenPathway: 'UNHCR biometric systems create dependency; aid-linked classification',
    reentryCondition: 'Refugee camp registration errors create permanent exclusion from services',
    classificationRisk: 'Very high — AI training data extracted without consent; misclassification rates elevated',
    lifeworldImpact: 'Dignity violations in biometric collection; aid conditionality',
    ecologicalImpact: 'E-waste dumping; data center cooling water use in drought-prone regions',
    correctionMechanism: 'AU data governance frameworks; community-led audits',
    scenarioInterpretation: 'Reform scenario funds data sovereignty; intensification deepens aid-system dependency',
  },
  {
    id: 'ME', label: 'Middle East', objectType: 'Region', systemLayer: 'planetary',
    lat: 25, lon: 45, nodeCategory: 'region',
    metrics: { FDCR: 29, GFDCR: 26, EFDCR: 23, BTR: 74, EER: 36, FGR: 32 },
    affectedActors: 'Stateless persons, migrant workers, conflict-displaced populations',
    affectedScale: 'Regional',
    burdenPathway: 'Kafala system binds worker status to employer; AI deportation targeting',
    reentryCondition: 'Nationality revocation leaves populations permanently unclassifiable',
    classificationRisk: 'Extreme — testimony erasure in AI asylum processing',
    lifeworldImpact: 'Physical confinement linked to digital status; family separation via classification',
    ecologicalImpact: 'Oil-linked data center energy; desalination pressure from population displacement',
    correctionMechanism: 'UNHCR statelessness campaigns; ILO labor standards',
    scenarioInterpretation: 'Reform scenario mandates kafala abolition; intensification expands deportation AI',
  },
  {
    id: 'SA_REG', label: 'South Asia', objectType: 'Region', systemLayer: 'planetary',
    lat: 20, lon: 78, nodeCategory: 'region',
    metrics: { FDCR: 40, GFDCR: 37, EFDCR: 34, BTR: 65, EER: 42, FGR: 44 },
    affectedActors: 'Stateless communities, caste minorities, climate migrants',
    affectedScale: 'Regional',
    burdenPathway: 'Aadhaar exclusions from food and welfare systems; biometric failure cascades',
    reentryCondition: 'Biometric failure = service denial; no offline fallback',
    classificationRisk: 'High — caste and religion as proxy variables in benefit algorithms',
    lifeworldImpact: 'Hunger linked to system errors; reproductive rights documentation failures',
    ecologicalImpact: 'Monsoon disruption displaces populations into unregistered status',
    correctionMechanism: 'Supreme Court oversight; civil society digital rights advocacy',
    scenarioInterpretation: 'Reform scenario creates offline identity fallback; intensification scales Aadhaar mandates',
  },
  {
    id: 'EX_CONGO', label: 'DRC Extraction Zone', objectType: 'Extraction Node', systemLayer: 'planetary',
    lat: -4, lon: 28, nodeCategory: 'extraction',
    metrics: { FDCR: 18, GFDCR: 15, EER: 12, BTR: 88, FGR: 20 },
    affectedActors: 'Artisanal miners, indigenous communities, child laborers',
    affectedScale: 'Local-Global',
    burdenPathway: 'Cobalt extraction for AI hardware batteries; no supply chain accountability',
    reentryCondition: 'Contamination of land renders communities unreturnable',
    classificationRisk: 'Extreme — workers invisible in AI supply chain classification',
    lifeworldImpact: 'Health burdens from mining; education denial; community displacement',
    ecologicalImpact: 'Soil and water contamination; biodiversity loss; carbon release from deforestation',
    correctionMechanism: 'Due diligence legislation; supply chain transparency mandates',
    scenarioInterpretation: 'Reform scenario funds extraction transition; intensification expands cobalt demand',
  },
  {
    id: 'EX_AMAZON', label: 'Amazon Extraction Zone', objectType: 'Extraction Node', systemLayer: 'planetary',
    lat: -5, lon: -62, nodeCategory: 'extraction',
    metrics: { FDCR: 22, GFDCR: 19, EER: 15, BTR: 84, FGR: 24 },
    affectedActors: 'Indigenous communities, forest peoples, future generations',
    affectedScale: 'Global',
    burdenPathway: 'Carbon offset algorithms displace communities; soy and cattle data used in financial AI',
    reentryCondition: 'Deforested land cannot regenerate within human timescales',
    classificationRisk: 'High — indigenous land rights erased by algorithmic resource mapping',
    lifeworldImpact: 'Cultural destruction; medicinal knowledge loss; food sovereignty erosion',
    ecologicalImpact: 'Tipping point risk; Amazon dieback would accelerate global climate burden',
    correctionMechanism: 'Forest protection legislation; indigenous territorial recognition',
    scenarioInterpretation: 'Reform scenario funds indigenous guardianship; intensification opens extraction corridors',
  },
  {
    id: 'AI_US', label: 'US AI Compute Cluster', objectType: 'Compute Node', systemLayer: 'planetary',
    lat: 41, lon: -96, nodeCategory: 'compute',
    metrics: { FDCR: 44, GFDCR: 41, EER: 35, BTR: 60, EPBTM: 65 },
    affectedActors: 'All users of AI classification systems; downstream populations',
    affectedScale: 'Global',
    burdenPathway: 'Training data biases from US systems propagate globally via model exports',
    reentryCondition: 'Model updates opaque; no mechanism for reclassification after error',
    classificationRisk: 'High — facial recognition and NLP models trained on non-representative data',
    lifeworldImpact: 'Biased hiring, credit, and welfare decisions affect millions',
    ecologicalImpact: 'Water and electricity consumption equivalent to small cities',
    correctionMechanism: 'NIST AI Risk Management; FTC enforcement; algorithmic auditing',
    scenarioInterpretation: 'Reform scenario mandates model cards and audits; intensification scales unaudited deployment',
  },
  {
    id: 'AI_CN', label: 'China AI Compute Cluster', objectType: 'Compute Node', systemLayer: 'planetary',
    lat: 35, lon: 115, nodeCategory: 'compute',
    metrics: { FDCR: 28, GFDCR: 25, EER: 30, BTR: 72, EPBTM: 70 },
    affectedActors: 'Citizens, minorities, political activists, export-market populations',
    affectedScale: 'Global',
    burdenPathway: 'Surveillance AI exported to authoritarian states; Xinjiang models replicated',
    reentryCondition: 'No legal mechanism for individuals to contest social credit scores',
    classificationRisk: 'Extreme — ethnicity as explicit classification variable',
    lifeworldImpact: 'Movement restriction; association chilling; digital identity revocation',
    ecologicalImpact: 'Coal-powered data centers; hardware manufacturing pollution',
    correctionMechanism: 'International sanctions; export controls on surveillance technology',
    scenarioInterpretation: 'Reform scenario builds international AI governance; intensification exports surveillance infrastructure',
  },
  {
    id: 'AI_EU', label: 'EU AI Compute Cluster', objectType: 'Compute Node', systemLayer: 'planetary',
    lat: 53, lon: 8, nodeCategory: 'compute',
    metrics: { FDCR: 58, GFDCR: 55, EER: 48, BTR: 50, EPBTM: 52 },
    affectedActors: 'EU citizens, third-country nationals, platform workers',
    affectedScale: 'Continental',
    burdenPathway: 'GDPR compliance burden falls on individuals; AI Act implementation gaps',
    reentryCondition: 'Right to explanation limited in practice; DPA backlogs create delay',
    classificationRisk: 'Moderate — legal frameworks partially effective',
    lifeworldImpact: 'Consent fatigue; data portability barriers; automated decision opacity',
    ecologicalImpact: 'Renewable energy transition underway; residual nuclear and gas dependency',
    correctionMechanism: 'GDPR enforcement; EU AI Act auditing; data protection authorities',
    scenarioInterpretation: 'Reform scenario strengthens enforcement; intensification weakens DPA funding',
  },
  {
    id: 'GULF_HUB', label: 'Gulf Logistics Hub', objectType: 'Logistics Node', systemLayer: 'planetary',
    lat: 24, lon: 54, nodeCategory: 'logistics',
    metrics: { FDCR: 32, GFDCR: 29, BTR: 70, EER: 38, FGR: 35 },
    affectedActors: 'Migrant workers, air cargo workers, seafarers',
    affectedScale: 'Regional-Global',
    burdenPathway: 'Passport confiscation by employers; AI border systems classify workers as security risks',
    reentryCondition: 'Labor ban lists prevent return migration for years',
    classificationRisk: 'High — nationality as primary risk variable in logistics AI',
    lifeworldImpact: 'Physical confinement; debt bondage; identity document seizure',
    ecologicalImpact: 'Aviation and shipping emissions; oil refinery co-location',
    correctionMechanism: 'ILO conventions; migrant worker advocacy; passport seizure bans',
    scenarioInterpretation: 'Reform scenario establishes worker portals; intensification expands deportation logistics',
  },
  {
    id: 'CLIMATE_PACIFIC', label: 'Pacific Climate Node', objectType: 'Climate Pressure Zone', systemLayer: 'planetary',
    lat: -8, lon: 170, nodeCategory: 'climate',
    metrics: { FDCR: 14, GFDCR: 11, EER: 8, BTR: 92, FGR: 16 },
    affectedActors: 'Pacific island communities, future generations, climate refugees',
    affectedScale: 'Global',
    burdenPathway: 'Sea level rise creates climate statelessness; no legal category for climate refugees',
    reentryCondition: 'Submersion of territory = permanent displacement; no return condition possible',
    classificationRisk: 'Extreme — climate displacement not recognized in refugee law',
    lifeworldImpact: 'Cultural extinction risk; ancestral land loss; forced diaspora',
    ecologicalImpact: 'Coral reef collapse; fishery destruction; freshwater salinization',
    correctionMechanism: 'Climate refugee legal frameworks; loss and damage fund; relocation agreements',
    scenarioInterpretation: 'Reform scenario creates climate refugee status; intensification delays loss-and-damage funding',
  },
  {
    id: 'WASTE_PACIFIC', label: 'Pacific E-Waste Zone', objectType: 'Waste Node', systemLayer: 'planetary',
    lat: 20, lon: 160, nodeCategory: 'waste',
    metrics: { FDCR: 16, GFDCR: 13, EER: 10, BTR: 90, FGR: 18 },
    affectedActors: 'Island communities, informal waste workers, marine ecosystems',
    affectedScale: 'Regional',
    burdenPathway: 'E-waste from AI hardware disposed via informal channels; plastic accumulation in Pacific gyre',
    reentryCondition: 'Contamination is generational; no cleanup mechanism at scale',
    classificationRisk: 'Moderate — waste workers lack occupational classification and protections',
    lifeworldImpact: 'Health impacts from toxic exposure; fishing ground destruction',
    ecologicalImpact: 'Marine microplastics; heavy metal leaching; ecosystem collapse',
    correctionMechanism: 'Extended producer responsibility laws; e-waste take-back schemes',
    scenarioInterpretation: 'Reform scenario mandates hardware lifecycle accountability; intensification deregulates waste exports',
  },
]

export const BURDEN_ARCS: Array<{
  id: string; from: string; to: string
  arcColor: string; label: string; flowType: string
}> = [
  { id: 'arc_ai_extract', from: 'AI_US', to: 'EX_CONGO', arcColor: '#ef4444', label: 'Hardware extraction burden', flowType: 'burden' },
  { id: 'arc_ai_climate', from: 'AI_US', to: 'CLIMATE_PACIFIC', arcColor: '#f97316', label: 'Energy → climate', flowType: 'burden' },
  { id: 'arc_cn_export', from: 'AI_CN', to: 'ME', arcColor: '#ef4444', label: 'Surveillance export', flowType: 'burden' },
  { id: 'arc_na_la', from: 'NA', to: 'LA', arcColor: '#f97316', label: 'Deportation burden', flowType: 'burden' },
  { id: 'arc_eu_af', from: 'EU', to: 'AF', arcColor: '#f97316', label: 'E-waste transfer', flowType: 'burden' },
  { id: 'arc_extract_waste', from: 'EX_AMAZON', to: 'WASTE_PACIFIC', arcColor: '#ef4444', label: 'Carbon → ocean', flowType: 'burden' },
  { id: 'arc_eu_reform', from: 'EU', to: 'AI_EU', arcColor: '#4ade80', label: 'Regulatory feedback', flowType: 'freedom' },
  { id: 'arc_as_gulf', from: 'AS', to: 'GULF_HUB', arcColor: '#f97316', label: 'Labor migration burden', flowType: 'burden' },
]
